services:
  discord-support-bot-server:
    image: node:22
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports:
      - "8080:80"
    restart: unless-stopped