POST http://localhost:8080/api/chat
Content-Type: application/json

{
  "message": [
    ["user", "こんにちは。私は太郎です。質問していいですか？"],
    ["ai", "こんにちは、太郎さん！  もちろん、どうぞご質問ください！ どんなことでもお気軽にお尋ねくださいね。 お手伝いできることがあれば幸いです。"],
    ["user", "いつもハードランディングになってしまいます"]
  ]
}